# 環境設定値（開発）
# -----------------------------------------------------------------------------
# logging configurations
# -----------------------------------------------------------------------------
logging:
  file: log/${spring.batch.job.names}_debug.log
  file.max-size: 20MB
  file.max-history: 0
  level:
#    root: debug
    org.springframework.jdbc: debug
    jp.co.springbatch.sample: debug


# -----------------------------------------------------------------------------
# Sample Application configurations
# -----------------------------------------------------------------------------
sample:
  system-date: 20190101 # Override

  datasource:
    primary:
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      url: jdbc:db2://localhost:50000/mydb:currentSchema=MYSCHEMA;
      username: db2admin
      password: db2admin

    secondary:
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      url: jdbc:db2://localhost:50000/mydb:currentSchema=MYSCHEMA;
      username: db2admin
      password: db2admin

  file:
    db-to-file:
      path: data/test-outputs/dbToFile.csv

    trigger-file:
      path: data/test-outputs

  service:
    sample-rest-service:
      base-url: http://localhost:9080/sample-rest-service-webapi/api/v1
