# 環境設定値（共通）
spring:
#  main:
#    web-environment: false
  batch:
    initialize-schema: never
    job:
      enabled: true

logging:
  level:
    org:
      springframework:
        jdbc: debug
