# 環境設定値（共通）
# 小文字のkebab caseで定義すること
### FW設定 ###
spring:
#  main:
#    web-environment: false
  batch:
    initialize-schema: never
    job:
      enabled: true
  main:
    banner-mode: "off"

### アプリ設定 ###
sample:
  # yyyyMMdd
  system-date: 
