# -----------------------------------------------------------------------------
# Spring boot configurations
# -----------------------------------------------------------------------------
spring:
  batch:
    initialize-schema: never
    job:
      enabled: true
  main:
    banner-mode: "off"
    web-application-type: none


# -----------------------------------------------------------------------------
# Framework configurations
# -----------------------------------------------------------------------------
framework:
  system-date:
    use: false
    deemed-date: # format yyyyMMdd


# -----------------------------------------------------------------------------
# Sample Application configurations
# -----------------------------------------------------------------------------
sample:
  file:
    db-to-file:
      data-file:
        name: dbToFile.csv
      trigger-file:
        name: SAMPLE.yyyyMMdd.TRG
    
    file-to-db:
      data-file:
        name: fileToDb.csv
      trigger-file:
        name: SAMPLE.yyyyMMdd.TRG

  service:
    sample-rest-service:
      customers-api: ${sample.service.sample-rest-service.base-url}/customers

    spring-boot-service:
      base-url: http://gturnquist-quoters.cfapps.io/api
      random-api: ${sample.service.spring-boot-service.base-url}/random
