# 環境設定値（開発）
### FW設定 ###
spring:
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    url: jdbc:db2://localhost:50000/mydb:currentSchema=MYSCHEMA;
    username: db2admin
    password: db2admin

### ログ設定 ###
logging:
  file: log/${spring.batch.job.names}_debug.log
  file.max-size: 20MB
  file.max-history: 0
  level:
    org:
      springframework:
        jdbc: debug

### アプリ設定 ###
sample:
  random-spring-boot-quotation-service:
    url: http://gturnquist-quoters.cfapps.io/api/random
