
/* Drop Tables */

DROP TABLE T_CUSTOMER_FAMILY_RELATION;
DROP TABLE T_CUSTOMER;
DROP TABLE T_FAMILY;




/* Create Tables */

-- 顧客
CREATE TABLE T_CUSTOMER
(
	-- 顧客番号
	CUSTOMER_NO char(8) NOT NULL,
	-- 氏名漢字
	NAME_KANJI varchar(60) NOT NULL,
	-- 氏名カナ
	NAME_KANA varchar(60) NOT NULL,
	-- 性別
	GENDER char(1) NOT NULL,
	-- 生年月日
	BIRTYDAY date NOT NULL,
	-- 郵便番号
	ADDRESS_ZIP varchar(7) NOT NULL,
	-- 住所
	ADDRESS varchar(200) NOT NULL,
	-- バージョン
	VERSION int DEFAULT 1 NOT NULL,
	-- 作成ユーザーID
	CREATION_USER_ID varchar(10) DEFAULT '' NOT NULL,
	-- 作成日時
	CREATION_DATE timestamp DEFAULT CURRENT TIMESTAMP NOT NULL,
	-- 更新ユーザーID
	UPDATED_USER_ID varchar(10) DEFAULT '' NOT NULL,
	-- 更新日時
	UPDATED_DATE timestamp DEFAULT CURRENT TIMESTAMP NOT NULL,
	PRIMARY KEY (CUSTOMER_NO)
);


-- 顧客家族関連
CREATE TABLE T_CUSTOMER_FAMILY_RELATION
(
	-- 顧客番号
	CUSTOMER_NO char(8) NOT NULL,
	-- 家族番号
	FAMILY_NO char(8) NOT NULL,
	-- バージョン
	VERSION int DEFAULT 1 NOT NULL,
	-- 作成ユーザーID
	CREATION_USER_ID varchar(10) DEFAULT '' NOT NULL,
	-- 作成日時
	CREATION_DATE timestamp DEFAULT CURRENT TIMESTAMP NOT NULL,
	-- 更新ユーザーID
	UPDATED_USER_ID varchar(10) DEFAULT '' NOT NULL,
	-- 更新日時
	UPDATED_DATE timestamp DEFAULT CURRENT TIMESTAMP NOT NULL,
	PRIMARY KEY (CUSTOMER_NO, FAMILY_NO)
);


-- 家族
CREATE TABLE T_FAMILY
(
	-- 家族番号
	FAMILY_NO char(8) NOT NULL,
	-- 氏名漢字
	NAME_KANJI varchar(60) NOT NULL,
	-- 氏名カナ
	NAME_KANA varchar(60) NOT NULL,
	-- 性別
	GENDER char(1) NOT NULL,
	-- 生年月日
	BIRTYDAY date NOT NULL,
	-- バージョン
	VERSION int DEFAULT 1 NOT NULL,
	-- 作成ユーザーID
	CREATION_USER_ID varchar(10) DEFAULT '' NOT NULL,
	-- 作成日時
	CREATION_DATE timestamp DEFAULT CURRENT TIMESTAMP NOT NULL,
	-- 更新ユーザーID
	UPDATED_USER_ID varchar(10) DEFAULT '' NOT NULL,
	-- 更新日時
	UPDATED_DATE timestamp DEFAULT CURRENT TIMESTAMP NOT NULL,
	PRIMARY KEY (FAMILY_NO)
);



/* Create Foreign Keys */

ALTER TABLE T_CUSTOMER_FAMILY_RELATION
	ADD FOREIGN KEY (CUSTOMER_NO)
	REFERENCES T_CUSTOMER (CUSTOMER_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_CUSTOMER_FAMILY_RELATION
	ADD FOREIGN KEY (FAMILY_NO)
	REFERENCES T_FAMILY (FAMILY_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



